name: Build podcasts-analytics-lambda

on:
  push:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  podcasts-analytics-lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

      - name: Build and test
        env:
          CAPI_KEY: ${{secrets.CAPI_KEY}}
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt 'test;universal:packageBin'

      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() #runs even if there is a test failure
        with:
          files: junit-tests/*.xml
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-1
          role-to-assume: ${{secrets.GU_RIFF_RAFF_ROLE_ARN}}

      - uses: guardian/actions-riff-raff@v2
        with:
          configPath: riff-raff.yaml
          projectName: Off-platform::podcasts-analytics-lambda
          buildNumberOffset: 192
          contentDirectories: |
            podcasts-analytics-lambda:
              - target/universal/podcasts-analytics-lambda.zip
